BEGIN;

CREATE TABLE IF NOT EXISTS USERS (
Id SERIAL PRIMARY KEY,
Balance float DEFAULT 0.0 NOT NULL
);


CREATE TABLE IF NOT EXISTS TRANSACTIONS (
id SERIAL PRIMARY KEY,
Type INT NOT NULL,
UserId INT NOT NULL,
Amount INT NOT NULL,
Time DATE NOT NULL,
	 FOREIGN KEY(UserId)
	 REFERENCES Users(Id)
);
COMMIT;